### PR TITLE
Ability to connect to clusters using ExecProvider

### PR DESCRIPTION
**Pull request by ihyoudou**
This PR adds ability to connect to Kubernetes clusters that are using ExecProvider, for example Google Kubernetes Engine and AWS Elastic Kubernetes Engine.  
I did test it only on GKE cluster as right now i don't have access to EKS or AKS clusters, but I assume it should also work.

screenshot of 'nodes' tab showing gke nodes in seabird

### CODE REVIEW

**Comment by jgillich** [comment]
Thanks for the contribution! Only issue I see is that, once imported, it becomes invisible to the user and can't be modified. Could you add a field that indicates when an ExecProvider is set, with an option to remove the value? Thanks

**Comment by ihyoudou** [comment]
Okay, I will try to craft something over the weekend, for now I will mark this pr as draft

**Comment by ihyoudou** [comment]
Hey, I did add the UI controls for execprovider values, as there are a lot of settings I did add this as a new expander row. 
I would also like to hear what do you think about naming these fields? Should they be named 1:1 as in kubeconfig or make them more "human"?

image showing cluster connection details window

@nathanael-h for testing I did try connecting to EKS cluster running 1.28.5, but I got an error
```
unable to retrieve the complete list of server APIs: 
custom.metrics.k8s.io/v1beta1: stale GroupVersion discovery: custom.metrics.k8s.io/v1beta1, custom.metrics.k8s.io/v1beta2: 
stale GroupVersion discovery: custom.metrics.k8s.io/v1beta2 
```
Not sure if that is a problem with my cluster or cluster discovery code in seabird, it would be great if you could also test on your end.

**Comment by jgillich** [comment]
Is it necessary to display all fields? When I said "a field" I meant just one :wink: 

How about this:

Screenshot from 2024-02-05 20-05-16

It would display the command when the config exists, and the trash button would remove it. Users shouldn't need to modify the values, so I think it's best to keep it as simple as possible.

**Comment by SoMuchForSubtlety** [comment]
I tested your branch and it panics when reading my kubeconfig.

```bash
$ go run main.go |&pp
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: closure error: unexpected panic caught: runtime error: invalid memory address or nil pointer dereference

Closure added at:
	github.com/diamondburned/gotk4/pkg/glib/v2.IdleAdd at /var/home/jakob/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.1.0/glib/v2/glib.go:30348
	github.com/getseabird/seabird/ui.onChange[...].func1 at /var/home/jakob/Projects/seabird/ui/on.go:15
	runtime.goexit at /usr/lib/golang/src/runtime/asm_amd64.s:1650
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2328e22]


To see all goroutines, visit https://github.com/maruel/panicparse#gotraceback

1: running [locked]
    closure funcstack.go:104    (*FuncStack).Panicf(*FuncStack(0xc000035410), string(0x2adce4d, len=27), interface{}{0xc00022f668, 0x1, 0x1})
    closure funcstack.go:122    (*FuncStack).TryRepanic(*FuncStack(0x1))
            panic.go:914        panic(any{0x26747c0, 0x4bec3d0})
    ui      cluster_prefs.go:75 NewClusterPrefPage.func1(*Window(0x0), *Behavior(0x0), <unknown>(0xc000162330), 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    ui      on.go:16            onChange[...].func1.1()
    glib    glib.go:340         _gotk4_sourceFunc(gpointer(0x100b))
    v2      :13789              _Cfunc_g_application_run(0x51bdba0, 1, #1)
    v2      gio.go:41611        (*Application).Run.func3(*Application(0xc00046a0b0), []string(0x4 len=86260576 cap=<nil>))
    v2      gio.go:41611        (*Application).Run(*Application(0xc00047c090), []string(0xc0000400a0 len=1 cap=1))
    ui      application.go:64   (*Application).Run(*Application(0x2abf61a))
    main    main.go:21          main()
```


This patch should fix it
```patch
diff --git a/ui/cluster_prefs.go b/ui/cluster_prefs.go
index afaf958..c803a35 100644
--- a/ui/cluster_prefs.go
+++ b/ui/cluster_prefs.go
@@ -70,16 +70,18 @@ func NewClusterPrefPage(parent *gtk.Window, b *behavior.Behavior, active observe
 		p.ca.SetText(string(prefs.TLS.CAData))
 		p.bearer.SetText(string(prefs.BearerToken))
 
-		p.executeProvider.apiversion.SetText(string(prefs.ExecProvider.APIVersion))
-		p.executeProvider.command.SetText(string(prefs.ExecProvider.Command))
-		p.executeProvider.args.SetText(strings.Join(prefs.ExecProvider.Args, " "))
-		p.executeProvider.env.SetText(p.buildEnvString(prefs.ExecProvider.Env))
-		p.executeProvider.provideClusterInfo.SetActive(prefs.ExecProvider.ProvideClusterInfo)
-
-		for idx, val := range AuthInteractiveModes {
-			if val == string(prefs.ExecProvider.InteractiveMode) {
-				p.executeProvider.interactiveMode.SetSelected(uint(idx))
-				break
+		if prefs.ExecProvider != nil {
+			p.executeProvider.apiversion.SetText(string(prefs.ExecProvider.APIVersion))
+			p.executeProvider.command.SetText(string(prefs.ExecProvider.Command))
+			p.executeProvider.args.SetText(strings.Join(prefs.ExecProvider.Args, " "))
+			p.executeProvider.env.SetText(p.buildEnvString(prefs.ExecProvider.Env))
+			p.executeProvider.provideClusterInfo.SetActive(prefs.ExecProvider.ProvideClusterInfo)
+
+			for idx, val := range AuthInteractiveModes {
+				if val == string(prefs.ExecProvider.InteractiveMode) {
+					p.executeProvider.interactiveMode.SetSelected(uint(idx))
+					break
+				}
 			}
 		}
```

**Comment by SoMuchForSubtlety** [comment]
I can also confirm that EKS works :)

**Comment by ihyoudou** [comment]
@jgillich 
I think we need to at least display command, arguments and environmental variables fields, as AWS is using args and envs. We could get rid of `apiversion` and `providerclusterinfo` field.
I did push a new commit that gets rid of these fields and move rest of them into "normal" authentication row

@SoMuchForSubtlety thanks for testing! Added your fix

**Comment by jgillich** [comment]
Does the user need to modify arguments and env vars frequently? If not, we don't need to show these fields. You'd still store the full `ExecConfig` in preferences obviously, this is just about what to display.

**Pull request closed without merging**
